config/routes.rb
Guidelines::Application.routes.draw do

  get "activities/index"

  ActiveAdmin.routes(self)

  devise_for :admin_user, ActiveAdmin::Devise.config

  get "guidelines/topic"
  get "guidelines/topichospital"
  get "guidelines/topicspecialty"
  get "guidelines/favourite"
  get "profiles/show"
  get "guidelines/show"
  get "guidelines/topiccountry"

 

  devise_for :users

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
    get 'edit', to: 'devise/registrations#edit', as: :edit
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
    get 'about', to: 'about#about', as: :about
  end

  resources :guidelines
  get 'guidelines', to: 'guidelines#index', as: :guidelines
  get 'favourites', to: "favourites#show", as: :favourites
  get 'topics', to: 'guidelines#list', as: :topics
  get 'hospitals', to: 'guidelines#listhospital', as: :hospitals
  get 'specialties', to: 'guidelines#listspecialty', as: :specialties
  get 'countries', to: 'guidelines#listcountry', as: :countries

 resources :activities

  root :to => 'guidelines#index'

resources :guidelines do
  resources :comments

end

  

  

 

end

app/models/guideline.rb
class Guideline < ActiveRecord::Base

  include PublicActivity::Model
  tracked owner: ->(controller, model){controller && controller.current_user}


	def to_param
		"#{id} #{title}".parameterize
	end

  attr_accessible :content, :hospital, :title, :user_id, :guideline_id, :specialty, :updated_by, :current_user, :subtitle, :slug, :activities, :country
 
 belongs_to :user
 has_many :favourite_guidelines
 has_many :comments, :dependent => :destroy


  validates :content, presence: true,
            length: {minimum:2}


  validates :title, presence: true,
            length: {minimum:2}

  validates :country, presence: true,
            length: {minimum:2}

  validates :hospital, presence: true,
            length: {minimum:2}

validates_uniqueness_of :hospital, :scope => :title, :case_sensitive => false, :message => "There is already a guideline by this title for this hospital"

validates :user_id, presence: true

searchable do
  text :title
end

 before_save do |guideline|
      guideline.content = "http://#{content}" unless guideline.content=~/^https?:\/\//
  end 

end

app/controllers/guidelines_controller.rb
class GuidelinesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]

  def index
    if params[:search].present?
      @search = Sunspot.search(Guideline) do  
        fulltext params[:search]
      end
      @guidelines = @search.results
    else
      @guidelines = Guideline.order(:title).page(params[:page]).per(15)
    end
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @guidelines }
      end
  end

 def favourite
   type = params[:type]
   if type == "favourite"
      @guideline= Guideline.find_by_id(params[:guideline_id])
      current_user.favourite_guidelines.build(:guideline_id => @guideline.id).save
      redirect_to :back
    elsif type == "unfavourite"
      @guideline= Guideline.find_by_id(params[:guideline_id])
      current_user.favourite_guidelines.where(:guideline_id => @guideline.id).destroy_all
     redirect_to :back
    else
      # Type missing, nothing happens
      redirect_to :back, notice: 'Nothing happened.'
    end
  end
  

  def topic
    @guidelines = Guideline.find_all_by_title(params[:title])
    @speccount = @guidelines.count 
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @guidelines }
    end
  end

  def listcountry
    @list = Guideline.order(:country).uniq.pluck(:country)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @guidelines }
    end
  end
  

  def list
    @list = Kaminari.paginate_array(Guideline.order(:title).uniq.pluck(:title)).page(params[:page]).per(20)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @guidelines }
    end  
  end

  def listhospital
    @list = Guideline.order(:hospital).uniq.pluck(:hospital)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @guidelines }
    end
  end

  def listspecialty
    @speclist = Guideline.order(:specialty).uniq.pluck(:specialty)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @guidelines }
    end
  end

  def topiccountry
    @guidelines =  Guideline.order(:title).find_all_by_country(params[:country])
    @countcount = @guidelines.count
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @guidelines }
    end 
  end

  def topicspecialty
    @guidelines =  Guideline.order(:title).find_all_by_specialty(params[:specialty])
    @speccount = @guidelines.count
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @guidelines }
    end 
  end

  def topichospital
    @guidelines = Guideline.order(:title).find_all_by_hospital(params[:hospital])
    @speccount = @guidelines.count
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @guidelines }
    end
  end

  # GET /guidelines/1
  # GET /guidelines/1.json
  def show
    @guideline = Guideline.find(params[:id])
    
    if @guideline.updated_by
     @updated = User.find(@guideline.updated_by).profile_name
    end

    if User.find(@guideline.user_id)
     @created = User.find(@guideline.user_id).profile_name
    end
 
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @guideline }
    end
  end

 
  # GET /guidelines/new
  # GET /guidelines/new.json
  def new
    @guideline = Guideline.new
    @specialties = Guideline.order(:specialty).uniq.pluck(:specialty)
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @guideline }
    end
  end

  # GET /guidelines/1/edit
  def edit
      @guideline = Guideline.find(params[:id])
      @specialties = Guideline.order(:specialty).uniq.pluck(:specialty)
  end

  # POST /guidelines
  # POST /guidelines.json
  def create
    @guideline = current_user.guidelines.new(params[:guideline])

    respond_to do |format|
      
      if @guideline.save
        format.html { redirect_to @guideline, notice: 'Guideline was successfully created.' }
        format.json { render json: @guideline, status: :created, location: @guideline } 
      else
        @specialties = Guideline.order(:specialty).uniq.pluck(:specialty)
        format.html { render action: "new" }
        format.json { render json: @guideline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /guidelines/1
  # PUT /guidelines/1.json
  def update
    @guideline = Guideline.find(params[:id])
    
    respond_to do |format|
      if @guideline.update_attributes(params[:guideline].merge(updated_by: current_user.id))
        format.html { redirect_to @guideline, notice: 'Guideline was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "show" }
        format.json { render json: @guideline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guidelines/1
  # DELETE /guidelines/1.json
  def destroy
    @guideline = Guideline.find(params[:id])
    @guideline.destroy
    respond_to do |format|
      format.html { redirect_to guidelines_url }
      format.json { head :no_content }
    end
  end


end

app/helpers/guidelines_helper.rb
module GuidelinesHelper

end

app/views/guidelines/_form.html.erb
</br>
<%= simple_form_for(@guideline, html: {class: "form-horizontal"}) do |f| %>
  <% if @guideline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guideline.errors.count, "error") %> prohibited this guideline from being saved:</h2>

      <ul>
      <% @guideline.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <%= f.input :title, label: 'Title (e.g. Asthma for under 12 months)' %>
  <%= f.input :specialty, as: :select, collection: @specialties %> 
  <%= f.input :hospital, label: 'Organisation/Hospital' %>
  <%= f.input :country, as: :string%>
  <%= f.input :content, as: :string, label: 'Link' %>
 



  <div class="form-actions">
    <%= f.button :submit, :class => "btn btn-info btn-large" %>
  </div>
<% end %>

app/views/guidelines/edit.html.erb
<h1>Editing guideline</h1>

<%= render 'form' %>

<%= link_to 'Show', @guideline %> |
<%= link_to 'Back', guidelines_path %>

app/views/guidelines/index.html.erb
<%= paginate @guidelines %>

<div class="page-header">
	<% if @search %>
	<h1>Search Results for "<%= params[:search] %>"</h1>
	<% else %>
  <h1>All Guidelines</h1>
  <% end %>
</div>

<%= link_to "Add a New Guideline", new_guideline_path, class: "btn btn-success btn-large" %>



<% @guidelines.each do |guideline| %>

<div class="guidelinerow">
	<div class="row">
		
			<div class="guideline span10">
			  
			<p>Title: <%= link_to guideline.title, guideline
 %></p>
 			
			<strong> <a href="<%= guideline.content %>" target = '_blank'>Link to guideline</a> </strong>
			
			<p>Organisation: <%= guideline.hospital %></p>
			
			<% if guideline.specialty %>
				<p>Specialty: <%= guideline.specialty %></p>
			<% end %>
					<div class="meta">
						 
						  

						  <span class="admin">
						  
						  	<% if current_user %>
						    <%= link_to "Edit", edit_guideline_path(guideline) %> 
						   |
						    <%= link_to "Delete", guideline, method: :delete, data: { confirm: "Are you sure you want to delete this guideline?"} %>
						    <% end %>
						    
						  </span>

					</div>
			</div>
			
			<% if current_user %>
			<div class="span2">

				<% if !current_user.favourite_guidelines.select{|f| f.guideline_id==guideline.id}.any? %>
 					<%= link_to guidelines_favourite_path(guideline_id: guideline.id, type: "favourite"), method: "get", class: "btn btn-small btn-success main" do%>
 					<i class="icon icon-star"></i> Favourite
 					<% end %>
 				<% end %>
 				<% if current_user.favourite_guidelines.select{|f| f.guideline_id==guideline.id}.any? %>
 				<%= link_to guidelines_favourite_path(guideline_id: guideline.id, type: "unfavourite"), method: "get", class: "btn btn-small btn-danger main" do%>
 				<i class="icon-star-empty icon-white"></i> Unfavourite
 				<% end %>
 			
 			
 			<% end %>

 			<% if guideline.comments.any? %>
 					<%= link_to guideline, class: "btn btn-small main white" do%><%= guideline.comments.count %> 
 					<% if guideline.comments.count==1 %>
 						comment
 					<% else %>
 					comments 
 					<% end %>
 					<% end %>
 			<% else %>
 					<%= link_to guideline, class: "btn btn-inverse btn-small main" do%>Add a comment
 					<% end %>
 			<% end %>

 			
		</div>
 <% end %> 

				
			
		
	</div>
</div>
<% end %>

app/views/guidelines/list.html.erb
<%= paginate @list %>

<div class="page-header">
  <h1>Alphabetical List of Topics</h1>
</div>

<%= link_to "Add a New Guideline", new_guideline_path, class: "btn btn-success btn-large" %>

<table class="table table-striped table-hover">

		<% @list.each do |title| %>
		<tr>
			<td><%= link_to title, :action => :topic, :title => title %></td>
		</tr>

				  

				
	
<% end %>

app/views/guidelines/listcountry.html.erb
<div class="page-header">
  <h1>List of Countries</h1>
</div>

<%= link_to "Add a New Guideline", new_guideline_path, class: "btn btn-success btn-large" %>


	<table class="table table-striped table-hover">
			
			
		<% @list.each do |country| %>

		<tr class="tablerow">
			<td><%= link_to country, :action => :topiccountry, :country => country %></td>
		</tr>


		
		
		
		
	

<% end %>

app/views/guidelines/listhospital.html.erb
<div class="page-header">
  <h1>List of Organisations</h1>
</div>

<%= link_to "Add a New Guideline", new_guideline_path, class: "btn btn-success btn-large" %>


	<table class="table table-striped table-hover">
			
			
		<% @list.each do |hospital| %>

		<tr class="tablerow">
			<td><%= link_to hospital, :action => :topichospital, :hospital => hospital %></td>
		</tr>


		
		
		
		
	

<% end %>

app/views/guidelines/listspecialty.html.erb
<div class="page-header">
  <h1>Specialty List</h1>
</div>

<%= link_to "Add a New Guideline", new_guideline_path, class: "btn btn-success btn-large" %>


	<table class="table table-striped table-hover">
			
		<% @speclist.each do |specialty| %>

		<tr class="tablerow">
			<td><%= link_to specialty, :action => :topicspecialty, :specialty => specialty %></td>
		</tr>


	
		
		
		
		
	

<% end %>

app/views/guidelines/new.html.erb
<h1>New Guideline</h1>


<%= render 'form' %>

<%= link_to 'Back', guidelines_path %>

app/views/guidelines/show.html.erb
<h2>Guideline Info</h2>
<div class="guidelinerow">

	<div class="row">
			
			<div class="guideline span10">
			  	
				<p>Title: <%= link_to @guideline.title, @guideline %> </p>
				<strong> <a href="<%= @guideline.content %>", target = '_blank'>Link to guideline</a> </strong>
				<p>Hospital Name: <%= @guideline.hospital %></p>
			
				<% if @guideline.specialty %>
					<p>Specialty: <%= @guideline.specialty %></p>
				<% end %>

				<% if @created %>
					<p><i>Added by: <%= @created %> on <%= @guideline.created_at.strftime("%d %b %Y") %></i></p>
				<% end %>

				<% if @updated && (@created != @updated) %>
					<p><i>Updated by: <%= @updated %> on <%= @guideline.updated_at.strftime("%d %b %Y") %></i></p>
				<% end %>


				<div class="meta">
						 
						  <span class="admin">
						  
						  	<% if current_user %>
						    <%= link_to "Edit", edit_guideline_path(@guideline) %> 
						   |
						    <%= link_to "Delete", @guideline, method: :delete, data: { confirm: "Are you sure you want to delete this guideline?"} %>
						    <% end %>
						    
						  </span>

				</div>
			
			</div>

			<% if current_user %>
			
			<div class="span2">

				<% if !current_user.favourite_guidelines.select{|f| f.guideline_id==@guideline.id}.any? %>
 					<%= link_to guidelines_favourite_path(guideline_id: @guideline.id, type: "favourite"), method: "get", class: "btn btn-small btn-success main" do%>
 					<i class="icon icon-star"></i> Favourite
 					<% end %>
 				<% end %>
 				<% if current_user.favourite_guidelines.select{|f| f.guideline_id==@guideline.id}.any? %>
 				<%= link_to guidelines_favourite_path(guideline_id: @guideline.id, type: "unfavourite"), method: "get", class: "btn btn-small btn-danger main show" do%>
 				<i class="icon-star-empty icon-white"></i> Unfavourite
 					<% end %>
 				<% end %>
 			
 			
 			<% end %>

 			

 			</div>


					
	</div>
</div>
<% if current_user %>
<h2>Comments</h2>
	<% if @guideline.comments.count>0 %>
		<div class="line">
			<%= render @guideline.comments %>		
		</div>
		
	<% else %>
		<div class="line">
			No comments have been added yet - be the first!
		</div>
	<% end %>

<h2>Add a comment</h2>
<div class="line">
		
		<%= render 'comments/form'%>
</div>

<% else %>

	<div class="container">
		</br>
		<h3>You need to be logged in to see comments</h3>
	</div>
<% end %>

					

app/views/guidelines/topic.html.erb
<% @guidelines.each_with_index do |guideline, index| %>

<div class="page-header">

	<% if index==0 %>
	<h1><%= guideline.title %> Guidelines  - <%= @speccount %> in total</h1>
	
	<% end %>
</div>

<% end %>

<%= link_to "Add a New Guideline", new_guideline_path, class: "btn btn-success btn-large" %>


<% @guidelines.each do |guideline| %>
<div class="guidelinerow">
	<div class="row">
		
			<div class="guideline span10">
			  
			<p>Title: <%= link_to guideline.title, guideline %></p>
			<strong> <a href="<%= guideline.content %>" target = '_blank'>Link to guideline</a> </strong>
			<p>Hospital Name: <%= guideline.hospital %></p>
			<% if guideline.specialty %>
				<p>Specialty: <%= guideline.specialty %></p>
			<% end %>
					<div class="meta">
						 
						 
						 

						  <span class="admin">

						  	<% if guideline.user == current_user %>
						    <%= link_to "Edit", edit_guideline_path(guideline) %> 
						   |
						    <%= link_to "Delete", guideline, method: :delete, data: { confirm: "Are you sure you want to delete this guideline?"} %>
						    <% end %>
						  </span>

					</div>
			</div>
			<div class="span2">

			<% if current_user %>
				<% if !current_user.favourite_guidelines.select{|f| f.guideline_id==guideline.id}.any? %>
 					<%= link_to guidelines_favourite_path(guideline_id: guideline.id, type: "favourite"), method: "get", class: "btn btn-small btn-success topic" do%>
 					<i class="icon icon-star"></i> Favourite
 					<% end %>
 				<% end %>
 			<% if current_user.favourite_guidelines.select{|f| f.guideline_id==guideline.id}.any? %>
 				<%= link_to guidelines_favourite_path(guideline_id: guideline.id, type: "unfavourite"), method: "get", class: "btn btn-small btn-danger topic" do%>
 				<i class="icon-star-empty"></i> Unfavourite
 				<% end %>
 			<% end %>

 			<% if guideline.comments.any? %>
 					<%= link_to guideline, class: "btn btn-small main white" do%><%= guideline.comments.count %> comments <% end %>
 			<% else %>
 					<%= link_to guideline, class: "btn btn-inverse btn-small main" do%>Add a comment
 					<% end %>
 			<% end %>
 			</div>
		
 <% end %> 

				
			
		
	</div>
</div>

<% end %>

app/views/guidelines/topiccountry.html.erb
<% @guidelines.each_with_index do |guideline, index| %>
<div class="page-header">
	<% if index==0 %>
	<h1><%= guideline.country %> Guidelines - <%= @countcount %> in total</h1>
	
	<% end %>

</div>

<% end %>
<%= link_to "Add a New Guideline", new_guideline_path, class: "btn btn-success btn-large" %>



<% @guidelines.each do |guideline| %>
<div class="guidelinerow">
	<div class="row">
		
			<div class="guideline span10">
			  
			<p>Title: <%= link_to guideline.title, guideline %></p>
			<strong> <a href="<%= guideline.content %>" target = '_blank'>Link to guideline</a> </strong>
			<p>Hospital Name: <%= guideline.hospital %></p>
			<% if guideline.specialty %>
				<p>Specialty: <%= guideline.specialty %></p>
			<% end %>
					<div class="meta">
						 
						 
						 

						  <span class="admin">

						  	<% if guideline.user == current_user %>
						    <%= link_to "Edit", edit_guideline_path(guideline) %> 
						   |
						    <%= link_to "Delete", guideline, method: :delete, data: { confirm: "Are you sure you want to delete this guideline?"} %>
						    <% end %>
						  </span>

					</div>
			</div>
			<div class="span2">

			<% if current_user %>
				<% if !current_user.favourite_guidelines.select{|f| f.guideline_id==guideline.id}.any? %>
 					<%= link_to guidelines_favourite_path(guideline_id: guideline.id, type: "favourite"), method: "get", class: "btn btn-small btn-success topic" do%>
 					<i class="icon icon-star"></i> Favourite
 					<% end %>
 				<% end %>
 			<% if current_user.favourite_guidelines.select{|f| f.guideline_id==guideline.id}.any? %>
 				<%= link_to guidelines_favourite_path(guideline_id: guideline.id, type: "unfavourite"), method: "get", class: "btn btn-small btn-danger topic" do%>
 				<i class="icon-star-empty"></i> Unfavourite
 				<% end %>
 			<% end %>

 			<% if guideline.comments.any? %>
 					<%= link_to guideline, class: "btn btn-small main white" do%><%= guideline.comments.count %> comments <% end %>
 			<% else %>
 					<%= link_to guideline, class: "btn btn-inverse btn-small main" do%>Add a comment
 					<% end %>
 			<% end %>
 			</div>
		
 <% end %> 

				
			
		
	</div>
</div>
<% end %>

app/views/guidelines/topichospital.html.erb
<% @guidelines.each_with_index do |guideline, index| %>
<div class="page-header">
	<% if index==0 %>
	<h1><%= guideline.hospital %> Guidelines - <%= @speccount %> in total</h1>
	
	<% end %>

</div>

<% end %>
<%= link_to "Add a New Guideline", new_guideline_path, class: "btn btn-success btn-large" %>



<% @guidelines.each do |guideline| %>
<div class="guidelinerow">
	<div class="row">
		
			<div class="guideline span10">
			  
			<p>Title: <%= link_to guideline.title, guideline %></p>
			<strong> <a href="<%= guideline.content %>" target = '_blank'>Link to guideline</a> </strong>
			<p>Hospital Name: <%= guideline.hospital %></p>
			<% if guideline.specialty %>
				<p>Specialty: <%= guideline.specialty %></p>
			<% end %>
					<div class="meta">
						 
						 
						 

						  <span class="admin">

						  	<% if guideline.user == current_user %>
						    <%= link_to "Edit", edit_guideline_path(guideline) %> 
						   |
						    <%= link_to "Delete", guideline, method: :delete, data: { confirm: "Are you sure you want to delete this guideline?"} %>
						    <% end %>
						  </span>

					</div>
			</div>
			<div class="span2">

			<% if current_user %>
				<% if !current_user.favourite_guidelines.select{|f| f.guideline_id==guideline.id}.any? %>
 					<%= link_to guidelines_favourite_path(guideline_id: guideline.id, type: "favourite"), method: "get", class: "btn btn-small btn-success topic" do%>
 					<i class="icon icon-star"></i> Favourite
 					<% end %>
 				<% end %>
 			<% if current_user.favourite_guidelines.select{|f| f.guideline_id==guideline.id}.any? %>
 				<%= link_to guidelines_favourite_path(guideline_id: guideline.id, type: "unfavourite"), method: "get", class: "btn btn-small btn-danger topic" do%>
 				<i class="icon-star-empty"></i> Unfavourite
 				<% end %>
 			<% end %>

 			<% if guideline.comments.any? %>
 					<%= link_to guideline, class: "btn btn-small main white" do%><%= guideline.comments.count %> comments <% end %>
 			<% else %>
 					<%= link_to guideline, class: "btn btn-inverse btn-small main" do%>Add a comment
 					<% end %>
 			<% end %>
 			</div>
		
 <% end %> 

				
			
		
	</div>
</div>
<% end %>

app/views/guidelines/topicspecialty.html.erb
<% @guidelines.each_with_index do |guideline, index| %>

<div class="page-header">
	<% if index==0 %>
	<h1><%= guideline.specialty %> Guidelines  - <%= @speccount %> in total</h1>
	
	<% end %>

</div>

<% end %>
<%= link_to "Add a New Guideline", new_guideline_path, class: "btn btn-success btn-large" %>



<% @guidelines.each do |guideline| %>
<div class="guidelinerow">
	<div class="row">
		
			<div class="guideline span10">
			  
			<p>Title: <%= link_to guideline.title, guideline %></p>
			<strong> <a href="<%= guideline.content %>" target = '_blank'>Link to guideline</a> </strong>
			<p>Hospital Name: <%= guideline.hospital %></p>
			<% if guideline.specialty %>
				<p>Specialty: <%= guideline.specialty %></p>
			<% end %>
					<div class="meta">
						 
						 
						 

						  <span class="admin">

						  	<% if guideline.user == current_user %>
						    <%= link_to "Edit", edit_guideline_path(guideline) %> 
						   |
						    <%= link_to "Delete", guideline, method: :delete, data: { confirm: "Are you sure you want to delete this guideline?"} %>
						    <% end %>
						  </span>

					</div>
			</div>
			<div class="span2">

			<% if current_user %>
				<% if !current_user.favourite_guidelines.select{|f| f.guideline_id==guideline.id}.any? %>
 					<%= link_to guidelines_favourite_path(guideline_id: guideline.id, type: "favourite"), method: "get", class: "btn btn-small btn-success topic" do%>
 					<i class="icon icon-star"></i> Favourite
 					<% end %>
 				<% end %>
 			<% if current_user.favourite_guidelines.select{|f| f.guideline_id==guideline.id}.any? %>
 				<%= link_to guidelines_favourite_path(guideline_id: guideline.id, type: "unfavourite"), method: "get", class: "btn btn-small btn-danger topic" do%>
 				<i class="icon-star-empty"></i> Unfavourite
 				<% end %>
 			<% end %>

 			<% if guideline.comments.any? %>
 					<%= link_to guideline, class: "btn btn-small main white" do%><%= guideline.comments.count %> comments <% end %>
 			<% else %>
 					<%= link_to guideline, class: "btn btn-inverse btn-small main" do%>Add a comment
 					<% end %>
 			<% end %>
 			</div>
		
 <% end %> 

				
			
		
	</div>
</div>
<% end %>